var data = [
    {
        caption:"anglebaby",
        img:"anglebaby",
        desc:"anglebaby"
    },
    {
        caption:"刘诗诗",
        img:"刘诗诗",
        desc:"刘诗诗"
    },
    {
        caption:"吴亦凡",
        img:"吴亦凡",
        desc:"吴亦凡"
    },
    {
        caption:"周杰伦",
        img:"周杰伦",
        desc:"周杰伦"
    },
    {
        caption:"唐嫣",
        img:"唐嫣",
        desc:"唐嫣"
    },
    {
        caption:"姚笛",
        img:"姚笛",
        desc:"姚笛"
    },
    {
        caption:"张柏芝",
        img:"张柏芝",
        desc:"张柏芝"
    },
    {
        caption:"星爷",
        img:"星爷",
        desc:"星爷"
    },
    {
        caption:"李小璐",
        img:"李小璐",
        desc:"李小璐"
    },
    {
        caption:"李易峰",
        img:"李易峰",
        desc:"李易峰"
    },
    {
        caption:"杨幂",
        img:"杨幂",
        desc:"杨幂"
    },
    {
        caption:"anglebaby",
        img:"anglebaby",
        desc:"anglebaby"
    },
    {
        caption:"林志颖",
        img:"林志颖",
        desc:"林志颖"
    },
    {
        caption:"柳岩",
        img:"柳岩",
        desc:"柳岩"
    },
    {
        caption:"章子怡",
        img:"章子怡",
        desc:"章子怡"
    },
    {
        caption:"范冰冰",
        img:"范冰冰",
        desc:"范冰冰"
    },
    {
        caption:"谢霆锋",
        img:"谢霆锋",
        desc:"谢霆锋"
    },
    {
        caption:"赵丽颖",
        img:"赵丽颖",
        desc:"赵丽颖"
    },
    {
        caption:"邓紫棋",
        img:"邓紫棋",
        desc:"邓紫棋"
    },
    {
        caption:"高圆圆",
        img:"高圆圆",
        desc:"高圆圆"
    },
    {
        caption:"鹿晗",
        img:"鹿晗",
        desc:"鹿晗"
    }
];

